[symlinks]
"komorebi\\.config\\komorebi\\applications.json" = "C:\\Users\\u55398\\.config\\komorebi\\applications.json"
"komorebi\\.config\\komorebi\\komorebi.bar.json" = "C:\\Users\\u55398\\.config\\komorebi\\komorebi.bar.json"
"komorebi\\.config\\komorebi\\komorebi.json" = "C:\\Users\\u55398\\.config\\komorebi\\komorebi.json"
"komorebi\\.config\\whkdrc" = "C:\\Users\\u55398\\.config\\whkdrc"
"nvim\\.config\\nvim\\.editorconfig" = "C:\\Users\\u55398\\.config\\nvim\\.editorconfig"
"nvim\\.config\\nvim\\init.lua" = "C:\\Users\\u55398\\.config\\nvim\\init.lua"
"nvim\\.config\\nvim\\lazy-lock.json" = "C:\\Users\\u55398\\.config\\nvim\\lazy-lock.json"
"nvim\\.config\\nvim\\lua\\config\\keymaps.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\config\\keymaps.lua"
"nvim\\.config\\nvim\\lua\\config\\lazy.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\config\\lazy.lua"
"nvim\\.config\\nvim\\lua\\config\\options.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\config\\options.lua"
"nvim\\.config\\nvim\\lua\\plugins\\autocomplete.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\autocomplete.lua"
"nvim\\.config\\nvim\\lua\\plugins\\catppuccin.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\catppuccin.lua"
"nvim\\.config\\nvim\\lua\\plugins\\copilot.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\copilot.lua"
"nvim\\.config\\nvim\\lua\\plugins\\fzf.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\fzf.lua"
"nvim\\.config\\nvim\\lua\\plugins\\lsp-config\\servers.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\lsp-config\\servers.lua"
"nvim\\.config\\nvim\\lua\\plugins\\lsp.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\lsp.lua"
"nvim\\.config\\nvim\\lua\\plugins\\luasnip.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\luasnip.lua"
"nvim\\.config\\nvim\\lua\\plugins\\mini.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\mini.lua"
"nvim\\.config\\nvim\\lua\\plugins\\none-ls.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\none-ls.lua"
"nvim\\.config\\nvim\\lua\\plugins\\obsidian.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\obsidian.lua"
"nvim\\.config\\nvim\\lua\\plugins\\oil.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\oil.lua"
"nvim\\.config\\nvim\\lua\\plugins\\render-markdown.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\render-markdown.lua"
"nvim\\.config\\nvim\\lua\\plugins\\todo-comments.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\todo-comments.lua"
"nvim\\.config\\nvim\\lua\\plugins\\treesitter.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\treesitter.lua"
"nvim\\.config\\nvim\\lua\\plugins\\trouble.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\trouble.lua"
"nvim\\.config\\nvim\\lua\\plugins\\twilight.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\twilight.lua"
"nvim\\.config\\nvim\\lua\\plugins\\which-key.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\which-key.lua"
"nvim\\.config\\nvim\\lua\\plugins\\zenmode.lua" = "C:\\Users\\u55398\\.config\\nvim\\lua\\plugins\\zenmode.lua"
"starship\\.config\\starship\\starship.toml" = "C:\\Users\\u55398\\.config\\starship\\starship.toml"

[templates]
