[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[komorebi.files]
"komorebi" = "~"

[tmux.files]
"tmux" = "~"

[starship.files]
"starship" = "~"

[nvim.files]
"nvim" = "~"

[lazygit.files]
"lazygit" = { target = "~", type = "symbolic" }
